language: ruby

rvm:
  - 2.4.4

addons:
  postgresql: "9.4"


before_install:
  - gem install bundler -v '>= 2'
  - "echo 'gem: --no-document' > ~/.gemrc"
  - "echo '--colour' > ~/.rspec"
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

before_script:
  - bundle exec rake db:create db:migrate RAILS_ENV=test

cache:
  bundler: true
  directories:
    - node_modules
  yarn: true

install:
  - bundle update --bundler
  - bundle install
  - nvm install node v11.10.0
  - node -v
  - npm i -g yarn
  - yarn

script:
  - bundle exec rails webpacker:compile
  - xvfb-run "--server-args=-screen\ 0\ 1366x768x24" bundle exec rspec
  #- xvfb-run -a bundle exec rspec
  #- bundle exec rails spec