meta_product_name: "Kamelot"
meta_title: "Kamelot, LE site des fringues cool"
meta_description: "👖👕👖👕 Un site e-commerce qui propose des vêtements super cool blablablabla"
meta_image: "landing.png" # should exist in `app/assets/images/`
twitter_account: "@product_twitter_account"   # required for Twitter Cards