# secret_key_base: THERE WILL ALREADY BE SOME CRAZY STRING HERE. LEAVE IT THERE.
# twilio_account_sid:  <%= ENV.fetch("TWILIO_ACCOUNT_SID", "AC6fd3e600501cacac5ae051c76b46d02a") %>
# twilio_auth_token:  <%= ENV.fetch("TWILIO_AUTH_TOKEN", "b26a3cf44674d6e42a9a7edd12a4dbbb") %>
# twilio_phone_number:  <%= ENV.fetch("TWILIO_PHONE_NUMBER", "+33644604541") %>
# admin_phone_number: <%= ENV.fetch("MY_PERSONAL_PHONE_NUMBER",  "+33674157645") %>
#   #TWILIO_PHONE_NUMBER:  "+33644604541"

# production:
#   TWILIO_ACCOUNT_SID: "AC6fd3e600501cacac5ae051c76b46d02a"
#   TWILIO_AUTH_TOKEN: "b26a3cf44674d6e42a9a7edd12a4dbbb"
#   TWILIO_PHONE_NUMBER:  "+33644604541"
#   MY_PERSONAL_PHONE_NUMBER:  "+33674157645"


#developement
TWILIO_ACCOUNT_SID: "AC6fd3e600501cacac5ae051c76b46d02a"
TWILIO_AUTH_TOKEN: "b26a3cf44674d6e42a9a7edd12a4dbbb"
TWILIO_PHONE_NUMBER:  "+33644604541"
MY_PERSONAL_PHONE_NUMBER:  "+33674157645"


#developement
STRIPE_PUBLISHABLE_KEY: pk_test_ctQ00dRLop1DwqcYjAYeTLbY
STRIPE_SECRET_KEY: sk_test_pjHYCzWkRfvFy2fuvtukb3Ye
